"""added about_me to User

Revision ID: 50af0bb71635
Revises: 8c065f1dda19
Create Date: 2018-09-07 13:14:34.001578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50af0bb71635'
down_revision = '8c065f1dda19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
